### ISSUE TITLE
Calling Java interface in a loop hangs after some invocations.

### ISSUE THREAD

**Issue by objviv** [bartdag/py4j#155]
I have a Java application, which starts the GatewayServer. The GatewayServer is started with a Factory class. The Factory returns an instance of a Worker class which spins up multiple threads of execution. Each thread of execution also has several System.out.println() statements which I am trying to use for help with debugging.

On the python side, following is the code:

for num in range(1, 1000):
        print '<<< %d >>>' % num
        gateway = JavaGateway(auto_convert=True)
        worker = gateway.entry_point.getFactory().getWorkerInstance()
        output = worker.doWork(<dict>,<list of list of dict>,<dict>,<string>)
        gateway.close()
        print output

The Java side (GatewayServer) and python client are running on Windows.

After some amount of calls, the python client hangs and the Java side shows no System.out.println() calls either. I have to kill the GatewayServer and then the python client shows the below exception trace:

<<< 10 >>>
Error while sending or receiving.
Traceback (most recent call last):
  File "C:\TOOLS\PYTHON27\lib\site-packages\py4j\java_gateway.py", line 473, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Tools\Python27\Lib\socket.py", line 430, in readline
    data = recv(1)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
Error while sending or receiving.

**Comment by objviv** [comment]
Same issue is seen on CentOS 6.6. Looks like the receive on the socket back to the client just blocks and I am not sure why? It ran a little longer, but eventually blocked and I had to kill the test script.

<<< 97 >>>
^CTraceback (most recent call last):
  File "testPy4J.py", line 111, in <module>
    main(False)
  File "testPy4J.py", line 83, in main
    output = client.doWork(,,,)
  File "/usr/lib/python2.6/site-packages/py4j/java_gateway.py", line 536, in __call__
    answer = self.gateway_client.send_command(command)
  File "/usr/lib/python2.6/site-packages/py4j/java_gateway.py", line 364, in send_command
    response = connection.send_command(command)
  File "/usr/lib/python2.6/site-packages/py4j/java_gateway.py", line 473, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/lib64/python2.6/socket.py", line 433, in readline
    data = recv(1)
KeyboardInterrupt

**Comment by bartdag** [comment]
Hi, I would need more information to help you. Without the Java code it's very difficult to diagnose where the problem could be. From the first stack trace, it seems that the Python side sent a command and never received an answer.

A few questions or tips:

1. It looks like you are creating a JavaGateway instance at each iteration. This is clearly not optimal because it creates a new connection every loop iteration. Could you create the gateway before the loop and use it inside the loop?
2. Can you enable logging on the Java and Python sides: http://py4j.sourceforge.net/faq.html#how-to-turn-logging-on-off
3. Does worker.doWork() actually returns (it seems the Python side is not receiving anything, so does it receive the input and does it produce an output)?
4. Each call to doWork is handled by a different thread than the one running the GatewayServer. It should not be a problem, but since you mentioned that your code is multi-threaded, that may be a source of trouble.

**Comment by objviv** [comment]
1. Will do - initially I had the script written to start the gateway once, but trying to sort out the hangs, I moved it into the loop thinking that I need to force clean up of the socket connections.
2. I have logging turned on now.
3. It appears that worker.doWork() returns, based on what I can see from the logs. I will add more logs.
4. So, on the python side, the GIL means there is only one thread executing at one time. On the java side then the GatewayServer receives each *new* request and handles it in a thread? Is the join/get call on the server thread a blocking call or do you have a (hopefully configurable) timeout on it?

In my java program, the doWork() method instantiates instances of a class that implements Callable. Each Callable is then submitted to an ExecutorService and finally I iterate over them to call get() on each Callable. This is an experiment - I am trying to see if this will scale up in a high performing environment. So naturally, the logs will be large and may take time to sort thru, I am hoping if you have done any load/perf tests with this library?

**Comment by bartdag** [comment]
Regarding threading, on the Python side, unless you use the callback server (which you are not from what I see), there is only one thread. You could call a gateway server with multiple threads and Py4J will create connections as needed, but it does not manage threads.

On the Java side, I'm using the same basic structure as Apache or other threaded servers: the thread running GatewayServer waits on accept. Once it receives a connection request, it creates a thread that will handle the connection (both requests and responses). The main thread only dispatches connection requests so it is relatively fast and do only minimal work (e.g., it does not try to read the request content).

This is not an event loop design though: it does not use nio and it is limited by standard thread-oriented design.

Regarding performance, Py4J stays limited by its use of sockets (vs JNI interface) and text-based protocol (in my 2 yrs-old tests, it was faster for method calls than protobuf, but it was a lot slower when transferring large byte array). There are ways to reduce the number of roundtrips when performance is critical, but that will usually give a 2X or 4X speedup, not an order of magnitude.

If I understand correctly, the doWork method spins some threads (through an ExecutorService), but it only returns when all callables have returned, so doWork is a blocking call? Assuming that doWork always return, this should work with Py4J and I hope we will find the source of the problem.

**Comment by objviv** [comment]
Thanks for the overview, it helps.

doWork() is a blocking call yes - that is the intent. I think I may have found the source of the problem. Each thread I create inside doWork() is itself invoking a service on the network (over a socket connection), and I think the threads are being starved of resources on that end.

Once I have this issue resolved, I plan to stress test the application. If you wish, I can share my findings with you.

I have liked Py4J so far, and happy to help make it a better library.

**Comment by bartdag** [comment]
Hi, I guess the problem was fixed on your end? Did you find anything in your stress test?

**Comment by objviv** [comment]
Yes, the problem was fixed at my end. Stress tests showed that py4j worked without errors but overall thruput was roughly a factor of 3 slower than a pure Python solution. 

Thanks!
Vivek. 
571-242-2962.
