### ISSUE TITLE
close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

### ISSUE THREAD

**Issue by Yonanam** [bartdag/py4j#170]
Hi,
I'm running version 0.9, on windows, using: 
self.gateway = JavaGateway.launch_gateway(classpath=os.environ['CLASSPATH'],                                                 die_on_exit=True)

I get exception:
  File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 1537, in launch_gateway
    daemonize_redirect=daemonize_redirect)
  File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 178, in launch_gateway
    close_fds=True)
  File "C:\Python27\lib\subprocess.py", line 667, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

This didn't happen when i used version 0.8.2.1 .

**Comment by bartdag** [comment]
Sorry for the bug. Will try to fix it over the weekend. I finally have a stable windows VM on which to test Py4J before a release so hopefully I'll catch these bugs much earlier in the future.

**Comment by bartdag** [comment]
Latest commit should fix the issue.

**Comment by Yonanam** [comment]
Hi,
It now runs, however, the python program never exits, and the jvm remains open. I'm running this code sample:

**********************************
import os
from py4j.java_gateway import JavaGateway

jars_dir = 'D:/test/lib/*'  # Holds all necessary jars
os.environ['CLASSPATH'] = jars_dir
gateway = JavaGateway.launch_gateway(classpath=os.environ['CLASSPATH'], die_on_exit=True)
print "i'm here"
**********************************

Even when adding gateway.close() at the end of the code, the python program never exits.

**Comment by bartdag** [comment]
Can you try adding daemonize_redirect=True to the launch_gateway call?

Will need to add this to the doc.

**Comment by Yonanam** [comment]
Thank you, it seemed to solve the issue.
