### ISSUE TITLE
Move to circle ci

### ISSUE THREAD

**Issue by bartdag** [bartdag/py4j#182]
Travis is far from reliable and circle-ci proved to be extremely stable for our code at @resulto-admin .

**Comment by bartdag** [comment]
@243826 tests on circle ci should now run (more) smoothly.

**Comment by 243826** [comment]
Great! Thank you!! I see that the build has passed. I'll have to submit another pull request now to see that it works consistently ;-)

Do you have anything that I can contribute on?

**Comment by bartdag** [comment]
About the build: yes, it should give reliable results now! I hadn't realised before you told me that Travis-CI configuration was the main issue. I moved Py4J to Circle-CI, which also has the advantage of including all the versions of the various compilers and interpreters in each container.

About the issues to contribute to, here are three of them that require different level of expertise. Before writing the code, though, it might be better to post on the issue your implementation plans. Do not hesitate to ask clarification questions too:

#163 has I believe the most straightforward resolution (necessary for vertx open source project)

#172 would be useful to many folks but may have performance impact so it should be configurable. There is some research to conduct on the best strategy to assign unique IDs, ideally with some micro-benchmark to assess the performance impact.

#165 is actually a symptom of the lack of proper java build configuration. Ideally, I would like to move py4j to Gradle with a maven wrapper (to be able to release Py4J to sonatype central maven repository), default configuration for eclipse and intellij, and some default checks configured. This looks promising: https://github.com/palantir/gradle-baseline

Thanks a lot for your help!
