### ISSUE TITLE
Maven build script needs version to be explicity set

### ISSUE THREAD

**Issue by lessthanoptimal** [bartdag/py4j#186]
As is, the Maven build script in the latest git code doesn't work on my system. 

* Mint Linux 17.3.  
* Apache Maven 3.0.5

 Below is the error it generates:

[ERROR] /home/pja/projects/thirdparty/py4j/py4j-java/src/py4j/reflection/PythonProxyHandler.java:[73,2] error: annotations are not supported in -source 1.3
[ERROR] 
[ERROR] (use -source 5 or higher to enable annotations)
[ERROR] /home/pja/projects/thirdparty/py4j/py4j-java/src/py4j/reflection/PythonProxyHandler.java:[99,19] error: enhanced for loops are not supported in -source 1.3
[ERROR] 
[ERROR] (use -source 5 or higher to enable for-each loops)
[ERROR] /home/pja/projects/thirdparty/py4j/py4j-java/src/py4j/commands/CallCommand.java:[72,2] error: annotations are not supported in -source 1.3

that goes on for about 4 screen....

Had to modify pom.xml by specifying the javac version it should use to compile the code.  Probably 1.5 would have worked, but I specified 1.8:

	<build>
		<sourceDirectory>src/</sourceDirectory>
		<testSourceDirectory>test/</testSourceDirectory>
		<plugins>
		  <plugin>
		    <groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-compiler-plugin</artifactId>
		    <version>2.3.2</version>
		    <configuration>
		      <source>1.8</source>
		      <target>1.8</target>
		    </configuration>
		  </plugin>
		</plugins>
	</build>

**Comment by bartdag** [comment]
Thanks @lessthanoptimal , the previous commit should fix the issue. The only think I am not sure is the plugin version. I see that the current compiler plugin version is 3.3. Will it work well for previous version of maven? I left it to 2.3.2, but I'm tempted to just put the latest version (3.3). What do you think?

**Comment by lessthanoptimal** [comment]
Yeah I'm not sure.  I use Gradle primarily and found the solution through
Google.     I guess set it to 3.3 and see if it still compiles?

- Peter

On Fri, Jan 1, 2016 at 5:39 AM, Barthelemy Dagenais <
notifications@github.com> wrote:

> Thanks @lessthanoptimal <https://github.com/lessthanoptimal> , the
> previous commit should fix the issue. The only think I am not sure is the
> plugin version. I see that the current compiler plugin version is 3.3. Will
> it work well for previous version of maven? I left it to 2.3.2, but I'm
> tempted to just put the latest version (3.3). What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bartdag/py4j/issues/186#issuecomment-168306761>.
>



-- 
"Now, now my good man, this is no time for making enemies."    — Voltaire
(1694-1778), on his deathbed in response to a priest asking that he
renounce Satan.
