### ISSUE TITLE
Socket descriptor leak 

### ISSUE THREAD

**Issue by zsxwing** [bartdag/py4j#187]
Py4J JavaGateway (half-)closes CallbackConnection after 30 seconds of inactivity and creates new one next time, but that connection doesn't get closed on the python CallbackServer side and keep piling up until it exhausts all ports.

Reported by Antony Mayi in [SPARK-12617](https://issues.apache.org/jira/browse/SPARK-12617)

**Comment by bartdag** [comment]
This is a regression introduced in 0.8 (https://github.com/bartdag/py4j/commit/e83f8e63a87c12960f1117f67dfc0c3f4746c97a#diff-57939bf36a031b995f968b1d767cbc2cL1085). My bad :-(

The finally is not necessary here (and it might even be confusing) and I'll just left-indent the calls to close.

**Comment by zsxwing** [comment]
Just found `CallbackConnection` should be removed from `callback_server.connections` too. I will update this PR to fix it.

**Comment by bartdag** [comment]
@zsxwing you're right and this bug has always existed. You'll probably need a back reference to the CallbackServer.

Do you know if there are typically many concurrent callback connections in PySpark (just wondering about the performance of looping through the connections list and doing and identity comparison)?

**Comment by zsxwing** [comment]
> Do you know if there are typically many concurrent callback connections in PySpark (just wondering about the performance of looping through the connections list and doing and identity comparison)?

It should be only several connections. Only several callback requests per second

**Comment by bartdag** [comment]
I'll take this one. I'll see if I can use a collection of weak refs. Hopefully I'll be able to avoid using locking for the purpose of cleaning up.

**Comment by bartdag** [comment]
I believe I fixed the issue by:

1. Left-indenting the socket closing code: each time the Java side closes a socket, the Python side will also close it.

2. Using a WeakSet instead of a standard list to maintain the list of active connections.

I made several manual tests and I see that the sockets are correctly closed and the CallbackConnection are garbage collected.

I had to backport the WeakSet implementation from Python 2.7. Is Python 2.6 still a supported version for PySpark? Is there any plan to drop it in the near future?

**Comment by zsxwing** [comment]
ping @JoshRosen @rxin for the plan of removing Python 2.6 support.

**Comment by rxin** [comment]
See http://apache-spark-developers-list.1001551.n3.nabble.com/discuss-dropping-Python-2-6-support-td15885.html

I'm now in favor of dropping Python 2.6 support in Spark 2.0. 

But don't we need to backport this into Spark 1.6, which does need to support Python 2.6?

**Comment by zsxwing** [comment]
@rxin, I think we usually don't upgrade a dependency version in a maintenance branch. Right?

https://github.com/apache/spark/pull/10579 is the current workaround in Spark and we can merge it for branch 1.6.

**Comment by rxin** [comment]
OK SGTM then.

**Comment by bartdag** [comment]
I have no problem with keeping Python 2.6 support for now as long as we can drop it in the foreseeable future. Thanks for the info.

**Comment by bartdag** [comment]
Please reopen if this does not fix the socket leak issue.

**Comment by bartdag** [comment]
I published the 0.9.1 release on pypi and maven (with Python 2.6 support).

**Comment by zsxwing** [comment]
Thanks @bartdag I will upgrade py4j for Spark.
