### ISSUE TITLE
py4j Exception: "Command Part is unknown: yn" when getting response from callback

### ISSUE THREAD

**Issue by saillsha** [bartdag/py4j#197]
Hello, I am trying to set up a callback server, but I'm getting an exception on the response back from the callback. The response from the callback server "!yn", while the Java side seems to expect the response to be just "yn". I'm not sure where the extra exclamation mark is coming from. Here's the log:

    Apr 19, 2016 6:12:20 PM py4j.CallbackClient getConnectionLock
    INFO: Getting CB Connection
    Apr 19, 2016 6:12:20 PM py4j.CallbackConnection start
    INFO: Starting Communication Channel on /127.0.0.1 at 25334
    Apr 19, 2016 6:12:20 PM py4j.CallbackClient getConnectionLock
    INFO: Acquired CB Connection
    Apr 19, 2016 6:12:20 PM py4j.CallbackConnection sendCommand
    INFO: Sending CB command: c
    p0
    notify
    ro0
    e
    Apr 19, 2016 6:12:20 PM py4j.CallbackConnection sendCommand
    INFO: Returning CB command: !yn
    Exception in thread "Thread-5" py4j.Py4JException: Command Part is unknown: yn
	at py4j.Protocol.getObject(Protocol.java:290)
	at py4j.Protocol.getReturnValue(Protocol.java:421)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:113)
	at com.sun.proxy.$Proxy2.notify(Unknown Source)
	at com.jwplayer.analytics.KafkaProcessor.KafkaConsumer$KafkaRunnable.run(KafkaConsumer.java:71)
	at java.lang.Thread.run(Thread.java:745)

And here's my python code:

```python
class MessageListener(object):
	def __init__(self):
		pass

	def notify(self, obj):
		print "notified by java", obj

	class Java:
		implements = ["com.jwplayer.analytics.KafkaProcessor.MessageListener"]

gateway = JavaGateway(start_callback_server=True, callback_server_parameters=CallbackServerParameters(),
	gateway_parameters=GatewayParameters())
gateway.entry_point.register(MessageListener())
gateway.entry_point.start_kafka(accounttoken)
```

And here's my java code:

```java
public class KafkaConsumer {
	private final ConsumerConnector consumer;
	private String analyticsToken;
	private MessageListener callback;
	public KafkaConsumer(){
		Properties props = new Properties();
               // properties removed
		this.consumer = kafka.consumer.Consumer.createJavaConsumerConnector(new ConsumerConfig(props));
	}

	public void register(MessageListener listener){
		callback = listener;
	}
	
	public void start_kafka(String analyticsToken){
		this.analyticsToken = analyticsToken;
		System.out.println(this.analyticsToken);
		Thread kafkaThread = new Thread(new KafkaRunnable());
		kafkaThread.start();
	}
	
	class KafkaRunnable implements Runnable {
		public void run() {
			Map<String, Integer> topicCount = new HashMap<String, Integer>();
			String kafkaTopic = "ping-avro";
			
			topicCount.put(kafkaTopic, new Integer(1));
			Map<String, List<KafkaStream<byte[], byte[]>>> consumerStreams = consumer
					.createMessageStreams(topicCount);
			List<KafkaStream<byte[], byte[]>> streams = consumerStreams
					.get(kafkaTopic);
			for(final KafkaStream stream : streams){
				ConsumerIterator<byte[], byte[]> consumerIte = stream.iterator();
				while(consumerIte.hasNext()){
					MessageAndMetadata<byte[], byte[]> mm = consumerIte.next();
					try{
			            SpecificDatumReader<Ping> reader = new SpecificDatumReader<Ping>(Ping.getClassSchema());
			            Decoder decoder = DecoderFactory.get().binaryDecoder(mm.message(), null);
			            Ping ping = reader.read(null, decoder);
			            Map<String, String> urlParameters = ping.getUrlParameters();
			            if(urlParameters.get("aid").equals(analyticsToken) &&
			            	(urlParameters.get("e").equals("s") || urlParameters.get("e").equals("tw") )){
			            	System.out.println(ping);
			            	callback.notify(ping);
			            }
					}
					catch(IOException e){
						e.printStackTrace();
					}
				}
			}
		}
	}

	public static void main(String[] args){
		GatewayServer gatewayServer = new GatewayServer(new KafkaConsumer());
		gatewayServer.turnLoggingOn();
		gatewayServer.start(true);
	}
}
```

Any help would be greatly appreciated. Thanks.

**Comment by bartdag** [comment]
Hi, the most likely explanation is that you are running a py4j python lib that is older than the py4j java lib. There was a change in the protocol between 0.9.2 and 0.10.0 that introduced a "!" for return messages. Can you confirm which version you are using on both sides?

**Comment by saillsha** [comment]
Yes that was the problem - I was using version 0.8.1 on the Java side. Upgrading to the latest version fixed the issue. Thanks for the quick reply.
