### ISSUE TITLE
Keep old versions available in pip

### ISSUE THREAD

**Issue by lessthanoptimal** [bartdag/py4j#199]
The recent release to 0.10.0 resulted in an unexpected forced upgrade because the upgrade broke existing code and there was no way to specify an older version.  Could you keep older versions available for install via pip?

**Comment by bartdag** [comment]
Hi, can you elaborate what you mean by keeping older versions available for install via pip?

**Comment by lessthanoptimal** [comment]
Was just writing a working example of what I'm talking about and it unexpectedly worked.   Guess I must have had a type-o.  However, https://pypi.python.org/pypi/py4j only showing 0.10.0 was also miss leading.  Now I'm not sure if it's supposed to show all available versions...

`sudo pip install -I py4j==0.9.2`

Also just noticed that py4j doesn't support `__version__`

```
import py4j
print py4j.__version__
AttributeError: 'module' object has no attribute '__version__'
```

Example of a package with it implemented:
```
In [5]: import numpy
In [6]: print numpy.__version__
1.8.2
```

**Comment by bartdag** [comment]
Regarding the previous releases, I always keep them but by default PyPI hides the previous releases. I changed the setting and all releases are now visible (they were still installable as you saw): https://pypi.python.org/pypi/py4j

Regarding the __version__ attribute, I was not aware of that but there are two peps that discuss this convention:
https://www.python.org/dev/peps/pep-0396/
https://www.python.org/dev/peps/pep-0440/

I'll add the attribute (it was already in py4j.version.__version__, but I'll make the necessary change so it is accessible from py4j).

**Comment by agronholm** [comment]
Instead of accessing `py4.__version__`, could you not do:
```python
import pkg_resources
version = pkg_resources.get_distribution('py4j').parsed_version
```
