### ISSUE TITLE
Large system call overhead caused by unbuffered readline() in java_gateway.py

### ISSUE THREAD

**Issue by kaytwo** [bartdag/py4j#201]
This line creates a file-like object for reading command responses from the JVM: https://github.com/bartdag/py4j/blob/master/py4j-python/src/py4j/java_gateway.py#L779. The 0 argument there forces the object to not perform any buffering. When combined with https://github.com/bartdag/py4j/blob/master/py4j-python/src/py4j/java_gateway.py#L828, receiving a large reply will cause recvfrom() system calls for every byte in the response. I'm seeing significant time spent in send_command() in a spark driver which I am pretty sure is due to this system call overhead.

Is there a reason for this socket to be unbuffered? I only see it used in a few `sendall`s and the `readline`. I don't see how the ssl context would mess anything up wrt buffering either.

Changing this socket to line buffered (or default buffering) would likely cause a measurable performance improvement.

**Comment by bartdag** [comment]
You are right. The socket is actually buffered on the Java side (BufferedReader and BufferedWriter). This is probably an oversight or a misunderstanding of my part of the 0 argument. I cannot use line buffering because I'm reading in binary mode and we are looking into pushing binary data so I'll just use default buffering. I'll see if I can come up with a small benchmark to measure performance improvement.

**Comment by kaytwo** [comment]
I just did a test on a simple Naive Bayes spark job using https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook

with character buffering:
```
real	1m30.209s
user	1m11.936s
sys	0m7.934s
```

with default buffering:
```
real	0m14.843s
user	0m4.215s
sys	0m0.241s
```

**Comment by bartdag** [comment]
Thanks for your tests and your suggestions. I wrote a small benchmark and although default buffering improve performance, the improvement is a lot smaller than what you observed (Mac OSX, Python2 and Python3, Java8). Considering the number of calls the benchmark is performing, maybe the size of the call arguments could explain the difference.

On which OS are you running your test (and which version of Python/Java are you using)?

Results from the benchmark:
```
Python3 before
9.45794415473938 - callStaticMethodNoParam
16.030117988586426 - callInstanceMethodWithShortParam
27.114354848861694 - callWithReflection
66.66643500328064 - constructorAndMemoryManagement
13.667526006698608 - javaCollection
39.53304386138916 - callBack

real    2m52.652s
user    1m34.810s
sys     0m32.687s

Python2 before
6.90571188927 - callStaticMethodNoParam
14.3549821377 - callInstanceMethodWithShortParam
23.4937832355 - callWithReflection
51.8541750908 - constructorAndMemoryManagement
10.5611710548 - javaCollection
31.4110569954 - callBack

real    2m18.757s
user    1m6.699s
sys     0m29.476s


Python3 after
5.6854870319366455 - callStaticMethodNoParam
13.580852031707764 - callInstanceMethodWithShortParam
22.682510137557983 - callWithReflection
51.48646903038025 - constructorAndMemoryManagement
10.712054014205933 - javaCollection
25.610312938690186 - callBack

real    2m9.942s
user    1m0.358s
sys     0m20.880s


Python2 after
4.99829888344 - callStaticMethodNoParam
12.7753760815 - callInstanceMethodWithShortParam
20.7793459892 - callWithReflection
47.5050489902 - constructorAndMemoryManagement
9.38175106049 - javaCollection
25.8335959911 - callBack

real    2m1.607s
user    0m59.358s
sys     0m19.341s
```

**Comment by kaytwo** [comment]
I added a little extra debugging output and found that I am receiving a 22,369,786 byte response as part of the py4j communication (all other responses are <100 bytes). I'm not using Spark in any nonstandard way - simply using the ML libraries that are included with it on some standard (not even very big) data.

environment:
```
jovyan@dfa9549dfa96:~/work$ uname -a
Linux dfa9549dfa96 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 GNU/Linux
jovyan@dfa9549dfa96:~/work$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
jovyan@dfa9549dfa96:~/work$ python --version
Python 3.5.1 :: Continuum Analytics, Inc.
jovyan@dfa9549dfa96:~/work$ 
```

**Comment by bartdag** [comment]
Thanks for the added information. I'll make sure that such a heavy response is represented in the benchmark I created. In any case, your contribution helped increase Py4J performance and I'm really happy with the result. I'll add you to the list of contributors if you have no objection.

**Comment by kaytwo** [comment]
I have no objection. Thanks for your quick investigation and fix. I've followed up in the Spark JIRA to try to get this update included there. Do you have a target date for 0.10.1?

**Comment by bartdag** [comment]
I added a benchmark with Python passing a 10 MB parameter and reading it back. The buffering improvement is now on par with what you observed (see longParamAndMemoryManagement)

```
Python3 before
9.759721994400024 - callStaticMethodNoParam
25.82467007637024 - callInstanceMethodWithShortParam
26.455302953720093 - callWithReflection
67.33186292648315 - constructorAndMemoryManagement
99.26946496963501 - longParamAndMemoryManagement
13.287966012954712 - javaCollection
41.79948306083679 - callBack

Python3 after
5.673011064529419 - callStaticMethodNoParam
22.923866033554077 - callInstanceMethodWithShortParam
22.834141969680786 - callWithReflection
53.09584712982178 - constructorAndMemoryManagement
1.6225168704986572 - longParamAndMemoryManagement
11.698266983032227 - javaCollection
31.44304585456848 - callBack
```

As a side note, Py4J was originally not designed to transfer large amount of data, and by large, I mean anything bigger than references. As the use cases increased, many users wanted to be able to transfer binary data between Python and the JVM because there was already a socket established between the two. I guess this shows how foreign that concept was to the Py4J codebase, but thanks to you and other contributors, Py4J is slowing approaching acceptable performance.

**Comment by bartdag** [comment]
Regarding releasing 0.10.1, I can do that soonish (in May), but I believe the biggest challenge will be in convincing Spark to spend the time to upgrade to 0.10.x.
