### ISSUE TITLE
Released jars require Java 8

### ISSUE THREAD

**Issue by agronholm** [bartdag/py4j#203]
Got this trying to launch a Py4J gateway with Oracle Java 7:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: py4j/GatewayServer : Unsupported major.minor version 52.0
```

**Comment by bartdag** [comment]
I guess it affects most released jars but which jar did you use? (Pypi or maven central?). I went through great length to make sure py4j is compiled with Java 6 bootstrap classes so I'm surprised this slipped through the cracks. I'll investigate and make sure to fix this by 0.10.1 due later this week.

**Comment by agronholm** [comment]
I installed from PyPI.

**Comment by bartdag** [comment]
Thanks a lot for noticing the problem. The gradle configuration has been updated. I'm releasing 0.10.1 now.

**Comment by agronholm** [comment]
Thanks for the quick fix!
