### ISSUE TITLE
Connection close on python callbackclient

### ISSUE THREAD

**Issue by scottslewis** [bartdag/py4j#231]
For the Python callbackclient, it closes the connection if the timeout (default 30s) expires.  I've found through testing that if the callback client is used after the timeout, then the data passed from Python to Java is not correct:  Python provides a non-null object and Java proxy is null where previous usage (prior to connection close) everything was fine.

**Comment by bartdag** [comment]
Hi, can you post a code snippet that can reproduce the problem? I would also need the version of Py4J, Python, Java, and the OS you are using.

This scenario (automatic connection cleanup) is part of the test suite so it's not obvious at first glance what the problem is.

**Comment by scottslewis** [comment]
Hi...through further testing, it turned out to be caused by something else unrelated to Py4j.  Closing bug.  Thanks for the quick attention.
