### ISSUE TITLE
ConcurrentModificationException upon python client disconnect

### ISSUE THREAD

**Issue by scottslewis** [bartdag/py4j#244]
Hi Barthelemy,

With the latest java code, when I forcibly kill the Python client, I'm consistently seeing this CME in the java-side GatewayServer:

WARNING: Error occurred while waiting for a command.
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
	at java.util.ArrayList$Itr.next(ArrayList.java:836)
	at py4j.GatewayServer.shutdown(GatewayServer.java:667)
	at py4j.GatewayServer.shutdown(GatewayServer.java:649)
	at py4j.commands.ShutdownGatewayServerCommand.execute(ShutdownGatewayServerCommand.java:66)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:744)

Not sure if this warning is expected, but I suspect not as it could leave things in an unclean state upon forcible remote disconnect.

**Comment by scottslewis** [comment]
Here's the full trace on java side:

Jul 26, 2016 10:15:25 AM py4j.GatewayServer fireServerStarted
INFO: Gateway Server Started
serverStarted
osgi> EvalConsumer.bindEval
Running eval('21+21')
EvalConsumer returns=42.0
Jul 26, 2016 10:15:55 AM py4j.GatewayServer fireConnectionStarted
INFO: Connection Started
connectionStarted c=py4j.GatewayConnection@586844af
Jul 26, 2016 10:15:55 AM py4j.GatewayConnection run
INFO: Gateway Connection ready to receive messages
Jul 26, 2016 10:15:55 AM py4j.CallbackClient getConnectionLock
INFO: Getting CB Connection
Jul 26, 2016 10:15:55 AM py4j.CallbackConnection start
INFO: Starting Communication Channel on /127.0.0.1 at 25334
Jul 26, 2016 10:15:55 AM py4j.CallbackClient getConnectionLock
INFO: Acquired CB Connection
Jul 26, 2016 10:15:55 AM py4j.CallbackConnection sendCommand
INFO: Sending CB command: c
p0
exportService
ro1
ao2
e

Jul 26, 2016 10:15:55 AM py4j.GatewayServer fireConnectionStarted
INFO: Connection Started
connectionStarted c=py4j.GatewayConnection@5005e1ab
Jul 26, 2016 10:15:55 AM py4j.GatewayConnection run
INFO: Gateway Connection ready to receive messages
Jul 26, 2016 10:15:55 AM py4j.CallbackConnection sendCommand
INFO: Returning CB command: yn
serverPreShutdown
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection run
WARNING: Unknown command null
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayServer fireServerError
SEVERE: Gateway Server Error
java.net.SocketException: socket closed
	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at py4j.GatewayServer.run(GatewayServer.java:632)
	at java.lang.Thread.run(Thread.java:744)

Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayServer fireServerStopped
INFO: Gateway Server Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.CallbackClient shutdown
INFO: Shutting down Callback Client
connectionStopped c=py4j.GatewayConnection@586844af
Jul 26, 2016 10:16:14 AM py4j.GatewayConnection run
WARNING: Error occurred while waiting for a command.
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
	at java.util.ArrayList$Itr.next(ArrayList.java:836)
	at py4j.GatewayServer.shutdown(GatewayServer.java:667)
	at py4j.GatewayServer.shutdown(GatewayServer.java:649)
	at py4j.commands.ShutdownGatewayServerCommand.execute(ShutdownGatewayServerCommand.java:66)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:744)

Jul 26, 2016 10:16:14 AM py4j.CallbackClient getConnectionLock
INFO: Getting CB Connection
Jul 26, 2016 10:16:14 AM py4j.CallbackClient getConnectionLock
INFO: Shutting down, no connection can be created.
Jul 26, 2016 10:16:14 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:14 AM py4j.reflection.PythonProxyHandler finalize
WARNING: Python Proxy ID could not send a finalize message: p0

**Comment by bartdag** [comment]
The concurrent modification is indeed unexpected but I don't understand what can be causing this. In the last commits, I only moved the fire postShutdown event inside the lock which seems unrelated to this error.

Can you give me more details about how you can reproduce the error? How/when do you kill the python process? It should not by itself shutdown the gateway server.

Also, what was the last version of the code that worked?

Thanks and sorry for the error

**Comment by bartdag** [comment]
I also see a strange thing in the trace: 

INFO: Shutting down Callback Client -> this indicates that the shutdown() method of CallbackClient was called,

but it should only be called after all connections have been visited in GatewayServer.shutdown.

I suspect the shutdown() methods may be called multiple times.

It should not be a problem by itself because the lock + boolean flag in a lock is supposed to be protecting the listeners list from concurrent access.

**Comment by scottslewis** [comment]
Hi Barthelemy,

>I suspect the shutdown() methods may be called multiple times.

I've verified this...I put a System.out.println in GatewayServer.shutdown, and it is called multiple times.   I can't tell whether it's a separate thread, or the same thread is reentering during connection.shutdown().

>Can you give me more details about how you can reproduce the error? How/when do you kill the >python process? It should not by itself shutdown the gateway server.

I am running the python process in the pydev/Eclipse debugger, and I kill it by stopping the process (red button).  

In the trace above, everything up until

...
INFO: Gateway Connection ready to receive messages
Jul 26, 2016 10:15:55 AM py4j.CallbackConnection sendCommand
INFO: Returning CB command: yn

Is with the Python process connecting and going through the exchange of OSGi service instances between java and Python.  This does have the Python server connection setup.

Then I hit the button and everything below occurs

serverPreShutdown
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection run
WARNING: Unknown command null
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayServer fireServerError
SEVERE: Gateway Server Error
java.net.SocketException: socket closed
at java.net.DualStackPlainSocketImpl.accept0(Native Method)
at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
at java.net.ServerSocket.implAccept(ServerSocket.java:545)
at java.net.ServerSocket.accept(ServerSocket.java:513)
at py4j.GatewayServer.run(GatewayServer.java:632)
at java.lang.Thread.run(Thread.java:744)

Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayServer fireServerStopped
INFO: Gateway Server Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:06 AM py4j.CallbackClient shutdown
INFO: Shutting down Callback Client
connectionStopped c=py4j.GatewayConnection@586844af
Jul 26, 2016 10:16:14 AM py4j.GatewayConnection run
WARNING: Error occurred while waiting for a command.
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
at java.util.ArrayList$Itr.next(ArrayList.java:836)
at py4j.GatewayServer.shutdown(GatewayServer.java:667)
at py4j.GatewayServer.shutdown(GatewayServer.java:649)
at py4j.commands.ShutdownGatewayServerCommand.execute(ShutdownGatewayServerCommand.java:66)
at py4j.GatewayConnection.run(GatewayConnection.java:214)
at java.lang.Thread.run(Thread.java:744)

Jul 26, 2016 10:16:14 AM py4j.CallbackClient getConnectionLock
INFO: Getting CB Connection
Jul 26, 2016 10:16:14 AM py4j.CallbackClient getConnectionLock
INFO: Shutting down, no connection can be created.
Jul 26, 2016 10:16:14 AM py4j.GatewayConnection fireConnectionStopped
INFO: Connection Stopped
Jul 26, 2016 10:16:14 AM py4j.reflection.PythonProxyHandler finalize
WARNING: Python Proxy ID could not send a finalize message: p0

**Comment by bartdag** [comment]
Hi Scott,

thanks for your help, I'll see if I can reproduce this error tonight.

One last question if I may. It looks like the Python side is sending a shutdown request (py4j.commands.ShutdownGatewayServerCommand.execute(ShutdownGatewayServerCommand.java:66)). Is it possible that you have something on the Python side that sends a shutdown request just before the Python process exits?

**Comment by scottslewis** [comment]
WRT your question about sending a shutdown request from Python...I don't do anything at the application level.   It would have to be something about the socket handling.   I'm not sure how the ShutdownGatewayServerCommand gets sent.

BTW, I've been looking at things a little bit and I've found that when a connection is stopped (e.g. inside of the GatewayServer.shutdown()) that it ends up calling GatewayServer.stop() ...e.g. stack like this:

Daemon Thread [Thread-3] (Suspended (breakpoint at line 626 in py4j.GatewayServer))	
	owns: org.py4j.internal.osgi.GatewayServer  (id=84)	
	owns: java.util.ArrayList<E>  (id=85)	
	py4j.GatewayServer.removeListener(py4j.GatewayServerListener) line: 626	
	org.py4j.internal.osgi.GatewayServer.doStop() line: 118	
	org.py4j.internal.osgi.GatewayServer.stop() line: 140	
	org.py4j.internal.osgi.GatewayServer$1.connectionStopped(py4j.Py4JServerConnection) line: 46	
	py4j.GatewayConnection.fireConnectionStopped() line: 151	
	py4j.GatewayConnection.shutdown(boolean) line: 259	
	py4j.GatewayConnection.shutdown() line: 237	
	py4j.GatewayServer.shutdown(boolean) line: 674	
	py4j.GatewayServer.shutdown() line: 653	
	py4j.commands.ShutdownGatewayServerCommand.execute(java.lang.String, java.io.BufferedReader, java.io.BufferedWriter) line: 66	
	py4j.GatewayConnection.run() line: 214	
	java.lang.Thread.run() line: 744	

Calling stop() results in the listeners being removed, which means subsequent notifications (e.g. serverStopped) do not occur.

**Comment by bartdag** [comment]
Hi Scott, unless I'm mistaken, 
```
py4j.GatewayServer.removeListener(py4j.GatewayServerListener) line: 626 
org.py4j.internal.osgi.GatewayServer.doStop() line: 118 
org.py4j.internal.osgi.GatewayServer.stop() line: 140
```

is part of your code. Py4J does not automatically remove external listeners (the only listener that is removed is the GatewayServer own listener when the GatewayServer thread is done).

**Comment by scottslewis** [comment]
Ah yes, you are correct!

**Comment by scottslewis** [comment]
Closing this bug.   AFAICT, it seems it was a mis-usage of the GatewayServerListener.   Sorry about the false alarm.

**Comment by bartdag** [comment]
Well, one thing I could do though is make a copy of the listeners before looping (on both sides) so a modification of the listeners would not raise that exception.

**Comment by scottslewis** [comment]
That's a good policy...I regularly do that as a precaution for notification.

**Comment by bartdag** [comment]
Sorry, I was confused for a second: the Java side is fine because it uses a CopyOnWriteArrayList which supports modifications while looping (even in the same thread). The signals make a copy of the receivers before firing an event so they both are good to go.

The concurrent modification was happening with the connection list which is a regular list. Making a copy will probably be faster than using one of the concurrent list because the list may be modified often and they are protected by a reentrant lock.

**Comment by bartdag** [comment]
I'll consider this as a bug: a listener badly behaving will be executing in the same thread as the shutdown method() and can thus reenter the shutdown method or play with the connections array.

Making a copy of the list of connections before looping is quick and would provide an additional layer of security on top of that.

I'll also add a guard in the shutdown method to make sure it cannot be called twice while iterating.

It's defensive programming at this point, but still
