### ISSUE TITLE
Allow disabling of automatic connection cleanup

### ISSUE THREAD

**Issue by scottslewis** [bartdag/py4j#246]
As discussed on this thread

https://github.com/bartdag/py4j/issues/240#issuecomment-236019413

It would be helpful for some use cases to be able to disable Py4j's automatic connection cleanup.  My suggestion would be to implement with one paramter...similar to socket read timeout that allows the connection clean up to be disabled (e.g. for value '0').

**Comment by scottslewis** [comment]
Hi Barthelemy...hope you are well.

Would it be possible for this issue to be addressed?   We are using py4j for an OSGi-based java app, and having the connection cleanup disable as soon as reasonable would be most helpful.

**Comment by bartdag** [comment]
Hi @scottslewis, I should be able to work on this next week. If I recall correctly, this was only on the Java side right?

**Comment by scottslewis** [comment]
To be honest I don't remember if it was only on the java side.

**Comment by bartdag** [comment]
After looking at the code (it's been a while), if you set a read timeout to 0 everywhere, the only remaining periodic cleanup is in CallbackClient.java, i.e., if Python calls Java, unused connections between Python and Java are cleaned up every 30 seconds. The "30 seconds" can be configured with the minConnectionTime and minConnectionTimeUnit parameters in the CallbackClient constructor.

I could add a condition that if minConnectionTime is set to 0, the periodic cleanup is disabled. Would that work with you?

**Comment by bartdag** [comment]
ping @scottslewis

**Comment by scottslewis** [comment]
Hi @bartdag .  Sorry I didn't respond previously.  Yes minConnectionTime set to 0 for disabling cleanup would be great.

Also, I have some work based upon Py4j for OSGi services integration that I can either release separately, or would consider contributing some of it to Py4j if you are interested.  How would you like to discuss?  Should I send email to you directly, or something else?

**Comment by bartdag** [comment]
I will implement minConnectionTime set to 0, ideally during this weekend.

Please keep it as a separated project for now. I'm already struggling to keep up with Py4J maintenance and development, I don't think I would be able to integrate your work in Py4J core in a timely manner :-(
