### ISSUE TITLE
Misprint in DOC example code

### ISSUE THREAD

**Issue by JuliaVikulina** [bartdag/py4j#254]
Hi!
Many thanks for py4j! 

I have noticed a misprint in documentation:
[https://www.py4j.org/advanced_topics.html#using-the-traditional-javagateway-gatewayserver](https://www.py4j.org/advanced_topics.html#using-the-traditional-javagateway-gatewayserver)
In the python example code **Gateway** is imported:
```python
from py4j.java_gateway import Gateway, CallbackServerParameters
```
but instead of it **JavaGateway** should be here.

Thank you.

**Comment by bartdag** [comment]
You are right, thanks for reporting this issue! Fixed in master.
