### ISSUE TITLE
How to get Java object's parameters?

### ISSUE THREAD

**Issue by xiaoleihuang** [bartdag/py4j#258]
The java method returns a list of java object, which may contain several variables, like person.name, person.age.
When I tried to use list_test[1].name, I only got 
```<py4j.java_gateway.JavaMember at 0x7ff2f8627048>```

How to fix it? Thank you.

**Comment by bartdag** [comment]
I believe you mean that list_test[1].name refers to a public field and not a method right? Please, see this answer in the FAQ for two strategies to get a field: https://www.py4j.org/faq.html#how-to-access-a-field.

**Comment by xiaoleihuang** [comment]
Hi, @bartdag 
Thank you! This works. BTW, alternatively, I tried to use methods like list_test[1].getName(), it worked as well, though no autocomplete if I use tab in ipython.

**Comment by jonahkichwacoders** [comment]
Hi @xiaoleihuang, I am curious about the missing auto-complete in IPython. Would you mind raising a separate ticket on that? Is it always reproducible the lack of completions, and which version of IPython?

**Comment by xiaoleihuang** [comment]
@jonahkichwacoders 
A separate ticket? What's that? A new issue?
My version is 5.1.0

**Comment by jonahkichwacoders** [comment]
Hi @xiaoleihuang, yes a new issue.
