### ISSUE TITLE
AttributeError: 'GatewayParameters' object has no attribute 'send_command'

### ISSUE THREAD

**Issue by xiaoleihuang** [bartdag/py4j#259]
Python 3.5
I tried to use 
`gateway = JavaGateway(GatewayParameters(auto_field=True))`

but an error prompted up:
File "demo.py", line 6, in <module>
    wrapper = gateway.entry_point.getWrapper()
  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1131, in __call__
    answer = self.gateway_client.send_command(command)
AttributeError: 'GatewayParameters' object has no attribute 'send_command'

**Comment by bartdag** [comment]
This is a documentation bug, but I thought I had fixed them all. Where did you see this particular example? You should use:

```gateway = JavaGateway(gateway_parameters=GatewayParameters(auto_field=True))
```

I saw one bad example in the warning just above https://www.py4j.org/getting_started.html#writing-the-python-program. Did you see this bad example in another place?

**Comment by bartdag** [comment]
rrrr. I found more examples in the FAQ and in the advanced topics section. Will fix them all. Sorry for the confusion.

**Comment by xiaoleihuang** [comment]
Hi, @bartdag 
Thank you for replying. Just let u know the link you shared me previously might cause the error:
https://www.py4j.org/faq.html#how-to-access-a-field
Best,
