### ISSUE TITLE
GatewayServer sends SocketException to listeners on shutdown

### ISSUE THREAD

**Issue by jvstein** [bartdag/py4j#260]
The GatewayServer sends a "java.net.SocketException: Socket closed" exception to all the listeners during server shutdown.

I'm starting the GatewayServer forked to a separate thread (i.e. `GatewayServer.start(true)`). The server class blocks on the `ServerSocket.accept` call in `GatewayServer.run` and when I'm done with the server I call `GatewayServer.shutdown` from my main thread. The socket needs to be destroyed as part of shutdown, but the internal details of the socket being closed doesn't need to be propagated to the listeners.

I'm working around it by maintaining a boolean "shutdown" flag and setting it from the `serverPreShutdown` call. I then specifically ignore any SocketException in the `serverError` method during shutdown. It would be nice to get rid of this guard code from my listeners.

Exception that is passed in:
```
java.net.SocketException: Socket closed
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at py4j.GatewayServer.run(GatewayServer.java:634)
        at java.lang.Thread.run(Thread.java:745)
```

py4j: 0.10.3
python: 2.7.12
java: 1.7
os: Ubuntu 16.04

**Comment by bartdag** [comment]
Right, the logging gets it right (this specific error is reported at the info level).
