### ISSUE TITLE
server not create on spark

### ISSUE THREAD

**Issue by momoxixi** [bartdag/py4j#261]
when i use py4j on spark with one machine,here is java code
`GatewayServer server = new GatewayServer(test,12345);
        server.start();`
and i run a python,here is python code
`gateway = JavaGateway(gateway_parameters=GatewayParameters(port=12345))
    test = gateway.entry_point`
but it print py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:12345)
and i use the linux cmd lsof -i:12345,it also can't be found.
I need any help. thanks

**Comment by bartdag** [comment]
Hi, unfortunately, I cannot offer support for Spark and you may have better luck asking them on their mailing list or on stackoverflow. The error you mention means that the Py4J GatewayServer is not started.
