### ISSUE TITLE
Could not find py4j jar when installed with pip install --user

### ISSUE THREAD

**Issue by davidcsterratt** [bartdag/py4j#266]
When py4j is installed using `pip install --user py4j` (pip version 8.1.1, python 2.7.12, as installed on Ubuntu 16.04), I get the following error:
```
>>> import py4j.java_gateway as jg
>>> port = jg.launch_gateway()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dcs/.local/lib/python2.7/site-packages/py4j/java_gateway.py", line 270, in launch_gateway
    raise Py4JError("Could not find py4j jar at {0}".format(jarpath))
py4j.protocol.Py4JError: Could not find py4j jar at 
```

**Comment by bartdag** [comment]
Thanks for your contribution. Pull request merged!

**Comment by davidcsterratt** [comment]
Thank-you! This will help with distributing my code.

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
