### ISSUE TITLE
UTF-8 handling Issue

### ISSUE THREAD

**Issue by cshwan96** [bartdag/py4j#269]
I seem to have asked prematurely.
i am confusing if this is my problem or py4j's problem..

[archive.zip](https://github.com/bartdag/py4j/files/870741/archive.zip)

**Comment by cshwan96** [comment]
i found a reason.

func.__call__("@\u03a1\u03a0\u000b\u000e\r\u000b\u039b\u0006\t\u0008\u0006\u0002\u0005\u0004\u0002}\u0001\u007f}y|{y" ,'\xcf', chr(46), chr(2))

func.__call__("@\u03a1\u03a0\u000b\u000e\r\u000b\u039b\u0006\t\u0008\u0006\u0002\u0005\u0004\u0002}\u0001\u007f}y|{y" ,'a', chr(46), chr(2))

second one is fine but first one throws error because it tries to decode '\xcf' which is in fact a char not string

**Comment by cshwan96** [comment]
public static String bЮ042E042EЮЮ042E042E042E042E042E(String arg1, int iarg2, int iarg3, int iarg4) {
    
    char arg2 = (char) iarg2;
    char arg3 = (char) iarg3;
    char arg4 = (char) iarg4;

    return wiiiii.b042E042E042EЮЮ042E042E042E042E042E(arg1, arg2, arg3, arg4).intern();
}

--------

g = JavaGateway()
wiiiii = g.jvm.iiiiii.wiiiii
print type(wiiiii)
func = wiiiii.__getattr__("bЮ042E042EЮЮ042E042E042E042E042E".decode('utf-8'))
print type(func)
re = func.__call__(u"H\u0428\u0014\u0017\u0016\u0014\u0423\u0422\u000e\u0011\u0010\u000e\n\r\u000c\n\u0006\t\u0008\u0006\u0002\u0005\u0004\u0002", 0x1d, 0x03, 0x02)
print re

--------
result for this is : bу0443уу0443044304430443 


i solved my problem by changing prototype to int which is supported by py4j currently.

how about using ctypes or gson library for more precise type supports?
if i have time later i will write a code for it.

**Comment by bartdag** [comment]
Hi, thanks for the debugging.

Are you sure that '\xcf' is valid utf-8 character? Python 2 seems to choke on it and Python 3 automatically converts it. This looks more like latin-1:

```
>>> s = '\xcf'
>>> s.encode("utf-8")
b'\xc3\x8f'
>>> s.encode("latin-1")
b'\xcf'
```

The conversion from String to char is tricky because Python has no concept of "char". Relying on a typed binary transport mechanism such as ctypes or gson, would not solve the type system mismatch between Python and Java: the user would also have to explicitly annotate each call argument, which is opposite to the goal of Py4J.

Although there are some unit tests testing similar cases, I'll check if sending a properly encoded \xcf works.

**Comment by cshwan96** [comment]
Thank you for your fast reply.
As you said, '\xcf' or '\x00\xcf' is not a "utf-8" encoding, but it is the problem that py4j always tries to encode it to utf-8.

In my case. function prototype has char arg; and in fact it is used as a number not a single utf-8 string.

In sum, py4j cannot handle the "JAVA Char" which its byte is out of the byte range of utf-8.

**Comment by bartdag** [comment]
Hi, this is really an encoding/decoding problem in user code. Consider this Java method:

```java
package examples;

public class EncodingTestClass {
    public void method1(char c) {
        System.out.println(c)
    }
}
```

Now consider this python 2 code:

```python
from py4j.java_gateway import JavaGateway
gateway = JavaGateway()
ex = gateway.jvm.examples.EncodingTestClass()
# This is a bytestring
s = '\xcf'
# su is now unicode
su = s.decode('latin-1')
ex.method1(su)
```

In other words, Py4J tries to automatically convert byte strings to unicode using utf-8. If you are using another encoding, you must decode the bytestring yourself.

**Comment by cshwan96** [comment]
thank you for introducing latin-1 encoding.

for me, below code completely solved the error.

`
import struct
def CHAR(short):
	string = struct.pack("<H",short)
	return string.decode('latin-1')

javamethod("aaaa",CHAR(0x4141),CHAR(0xcf))
`
