### ISSUE TITLE
float/doubles are rounded?

### ISSUE THREAD

**Issue by howarth** [bartdag/py4j#272]
Hello, here's some code

````
>>> d1
17.133574204226083
>>> str(d1)
'17.1335742042'
>>> repr(d1)
'17.133574204226083'
>>> f = mc.gateway.jvm.java.lang.Double(d1)
>>> f
17.1335742042
>>> f == d1
False
````
I would think that the last line should read True. However, it seems as though when a double (python float) goes from python to Java it is rounded in the same way that the str() function rounds the number

**Comment by bartdag** [comment]
Arrr... Did you try that with Python 2.7 by any chance? It seems that Python 3.x returns the same string for both str() and repr().

It seems the fix would be to explicitly call repr before smart_decode here: https://github.com/bartdag/py4j/blob/master/py4j-python/src/py4j/protocol.py#L216

The new protocol in 0.11.x solves this by packing the float in binary format: https://github.com/bartdag/py4j/blob/issue-249-binary-protocol/py4j-python/src/py4j/binary_protocol.py#L537

**Comment by howarth** [comment]
Is that branch usable at the moment?

**Comment by bartdag** [comment]
No, not done yet. And were you using Python 2.7?

**Comment by howarth** [comment]
Yes I was

**Comment by bartdag** [comment]
Fix now in master branch.
