### ISSUE TITLE
[Question] Coroutine/Asyncio support?

### ISSUE THREAD

**Issue by Restioson** [bartdag/py4j#273]
Does Py4J support asyncio/coroutines?

**Comment by bartdag** [comment]
Not natively no. I am not sure what the programming model would look like though because users usually expect a call to Java to block. What kind of usage scenario did you have in mind?

**Comment by Restioson** [comment]
Uhhh... It was a long time ago, but I was wondering whether I could do something with coroutines in kotlin and coroutines in python? Don't remember the details, sorry...
