### ISSUE TITLE
Client/Server transport corruption caused by py4j memory management 

### ISSUE THREAD

**Issue by jonahkichwacoders** [bartdag/py4j#275]
Hi Barthelemy,

I have been having occasional random exceptions with py4j (and its integration in Eclipse EASE) like the following:
```
py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:438)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:105)
	at com.sun.proxy.$Proxy25.executeScript(Unknown Source)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.internalExecute(Py4jScriptEngine.java:221)
	at org.eclipse.ease.lang.python.py4j.internal.Py4jScriptEngine.execute(Py4jScriptEngine.java:211)
	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:228)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

As it turns out this is caused by py4j memory management sending a memory delete (MEMORY_DEL_SUBCOMMAND_NAME) to the Java in the middle of receiving a command from Java. 

Here is an extract of a log, with comments (#)

```
May 31, 2017 12:38:57 PM py4j.ClientServerConnection sendCommand
INFO: Sending Python command: c  # Java starts calling Python
t
sendObject
ro96
ro97
e

Received command c on object id t  # Python receiving the call
Command to send: m  # in the middle of processing the call from Java, Python garbage collection start
d
o0
e

Answer received: e  # this e is the end of the Java call (after ro97)
Unknown command e
May 31, 2017 12:38:57 PM py4j.ClientServerConnection sendCommand
INFO: Returning CB command: x
py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: x
	at py4j.Protocol.getReturnValue(Protocol.java:449)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:109)
	at com.sun.proxy.$Proxy0.sendObject(Unknown Source)
	at py4j.examples.SingleThreadClientApplicationSendsObjects.main(SingleThreadClientApplicationSendsObjects.java:48)
```

I have an created a test, https://github.com/jonahkichwacoders/py4j/tree/memory_management_bug, that shows the problem. Note that slight changes to parameters, python versions, etc can cause the bug to appear more or less reliably. As I write this it occurs to me doing a forced gc in the middle of the receive code in Python may help make it more reliable?

**Comment by jonahkichwacoders** [comment]
Cross-reference to Eclipse EASE bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517528

**Comment by bartdag** [comment]
Hi Jonah,

I actually tested a slightly different case: garbage collection occurring in the middle of python client code execution. You are right that if garbage collection occurs in the middle of the Py4J network code, this will definitively be bad for the ClientServer transport (the regular JavaGateway will just create a new connection). I hadn't thought of this and writing a reliable test is indeed almost impossible :-(

Disabling and re-enabling gc around the network code should do the trick, but I'll have to test with your branch first. If this is still not reliable, another idea would be to create a dedicated thread for garbage collection and send garbage collection commands to this particular thread. I usually try to avoid creating invisible "management" threads though. We'll see. I should be able to work on this Thursday evening.

Which version of Python did you use to reproduce the error (might save me some time reproducing the error)?

**Comment by bartdag** [comment]
Hi Jonah,

I actually tested a slightly different case: garbage collection occurring in the middle of python client code execution. You are right that if garbage collection occurs in the middle of the Py4J network code, this will definitively be bad for the ClientServer transport (the regular JavaGateway will just create a new connection). I hadn't thought of this and writing a reliable test is indeed almost impossible :-(

Disabling and re-enabling gc around the network code should do the trick, but I'll have to test with your branch first. If this is still not reliable, another idea would be to create a dedicated thread for garbage collection and send garbage collection commands to this particular thread. I usually try to avoid creating invisible "management" threads though. We'll see. I should be able to work on this Thursday evening.

Which version of Python did you use to reproduce the error (might save me some time reproducing the error)?

**Comment by jonahkichwacoders** [comment]
```
$ python --version
Python 2.7.11 :: Continuum Analytics, Inc.
```

An additional option is to queue up the refs to be deleted and send them later on the same thread?

**Comment by bartdag** [comment]
Small update:

1. Disabling gc and forcing gc.collect() in ClientServerConnection._auto_gc does the trick.
2. Now I need to test if gc.disable() can be more fine-grained, but preliminary testing indicates it will be difficult.

Your test was very helpful in reproducing the bug!

**Comment by bartdag** [comment]
On twitter you mentioned a solution, queuing garbage collection requests until they are safe to process, that I wrongly dismissed because it would not work in a degenerate case. Stopping the GC globally is obviously a worse solution than the one you suggested 😳 Apologies for not seeing this earlier!!

I'll try the management thread approach first, which mirrors the way the JVM works, but will fall back to your suggestion if it is to cumbersome to manage.

**Comment by bartdag** [comment]
@jonahkichwacoders can you try the `issue-275-clientserver-memmanagement` branch. The fix should prevent bugs caused by garbage collection, but I want to be sure the management thread does not cause any conflict with EASE.

Thanks again for your test case, I don't think I could have fixed this bug without it.

**Comment by jonahkichwacoders** [comment]
Hi @bartdag Thanks for fixing this, I will try to test as soon as I can, but it won't be until next week.

**Comment by jonahkichwacoders** [comment]
@bartdag Looks good to me. Passes all the Py4J EASE tests.

PS I really like how you have removed the auto_gc. Although I haven't collected stats, I suspect that previously doing all the gc.collect was probably not good for the memory behaviour when py4j was in use because it meant that objects were being moved to older generation too easily.

**Comment by bartdag** [comment]
Thanks for testing it!

auto_gc was really a crutch to try to prevent the bug you reported :-( I'm was also happy to remove it!
