### ISSUE TITLE
ConcurrentModificationException when trying to connect from Java to Python using multiple threads

### ISSUE THREAD

**Issue by Nekdo** [bartdag/py4j#276]
When using `py4j.ClientServer` on java part and `py4j.clientserver.ClientServer` on python part I sometimes get `ConcurrentModificationException` when invoking python code from java. 

One such exception is here:

```
[info] Caused by: java.util.ConcurrentModificationException
[info] 	at java.util.ArrayDeque.delete(ArrayDeque.java:549)
[info] 	at java.util.ArrayDeque.removeFirstOccurrence(ArrayDeque.java:370)
[info] 	at java.util.ArrayDeque.remove(ArrayDeque.java:747)
[info] 	at py4j.PythonClient.getConnection(PythonClient.java:176)
[info] 	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:211)
[info] 	... 32 more
```

I think it is caused by the fact that the method
```
protected void giveBackConnection(Py4JClientConnection cc) {
	connections.addLast(cc);
}
```
in `py4j.PythonClient` calls `connections.addLast()` without any lock.

But the method `giveBackConnection` from `CallbackClient` class acquires the lock:
```
protected void giveBackConnection(Py4JClientConnection cc) {
	try {
		lock.lock();
		if (cc != null) {
			if (!isShutdown) {
				connections.addLast(cc);
			} else {
				cc.shutdown();
			}
		}
	} finally {
		lock.unlock();
	}
}
```

**Comment by bartdag** [comment]
I think you are right. ClientServer has been used mostly on one thread (the UI thread), which may explain why this problem never surfaced before. I'm surprised I missed that and that no user reported that error before, but the javadoc clearly states that ArrayDeque is not threadsafe and I even have a comment in connectionStopped saying that a lock should be used :-(

I'll add the missing lock in the methods that use the connections deque. Do you have an example that can reproduce the problem?

**Comment by Nekdo** [comment]
Sorry, I don't have a simple example I can share. I have hit this bug when using Py4J to call Pyhon on Apache Spark workers from Scala. I was not able to reproduce it under a simpler scenario. 

However, when I added the locking around `connections.addLast(cc)` call, I stopped seeing this bug.
