### ISSUE TITLE
Python exception propagation

### ISSUE THREAD

**Issue by scottslewis** [bartdag/py4j#277]
Hi Barthelemy,

I've noticed that when calling from Java to Python, if an exception occurs in Python code it is caught, but then not propagated back to Java.  i.e. in Python: java_gateway._call_proxy Method (2242):

    def _call_proxy(self, obj_id, input):
        return_message = proto.ERROR_RETURN_MESSAGE
        if obj_id in self.pool:
            try:
                method = smart_decode(input.readline())[:-1]
                params = self._get_params(input)
                return_value = getattr(self.pool[obj_id], method)(*params)
                return_message = proto.RETURN_MESSAGE + proto.SUCCESS +\
                    get_command_part(return_value, self.pool)
            except Exception:
                logger.exception("There was an exception while executing the "
                                 "Python Proxy on the Python Side.")
        return return_message

On exception in the call, it is caught and logged, but then the return_message...i.e. proto.ERROR_RETURN_MESSAGE is sent back to java.   This loses any/all information in the exception (i.e. what happened) in the failure.

Is there a way that the exception information...i.e. except Exception as e: could be included/sent back in the error return message?

On the Java side it may also be nice to have a Py4jPythonException...for symmetry with the Py4jJavaException.

In any case, what I'm looking for is a way to have the python exception information (message at least, stack trace desirable) included in the error so that it is/can be in the java exception.

**Comment by bartdag** [comment]
I believe this is a duplicate of #137 ?

**Comment by scottslewis** [comment]
Ok I'll join 137 thanks
