### ISSUE TITLE
PythonProxyHandler.convertOutput should allow null/None response

### ISSUE THREAD

**Issue by scottslewis** [bartdag/py4j#278]
Hi Barthelemy,

Consider a java interface method:

`String hello();`

If a python implementation of this service is:

`def hello(self):`
`    return None`

Then at runtime in PythonProxyHandler.convertOutput is this code:

`private Object convertOutput(Method method, Object output) {`
`	    Class<?> returnType = method.getReturnType();`
`	    Class<?> outputType = output.getClass();`
`	    if (returnType.equals(Void.TYPE)) {`
`		    // Do not convert void`
`		    return output;`
`	    }`
...
`

Object output will be null (None), and the call to output.getClass() will throw an NPE.

There should probably some logic preventing this...e.g.:

`private Object convertOutput(Method method, Object output) {`
`    Class<?> returnType = method.getReturnType();`
`     if (output == null || returnType.equals(Void.TYPE)) {`
`        return null;`
`     }`
`    Class<?> outputType = output.getClass();`
`    ...`

If desired I can/will create a pull request for this fix.  Please let me know.

**Comment by bartdag** [comment]
Hi Scott, do not hesitate to make a pull request. You can also add a test in java_callback_test.py (there is already a test for the VOID return type).

I think this bug is relatively new (when I added a return type converter). Thanks for reporting it!!

**Comment by dongjoon-hyun** [comment]
Hi, @bartdag .
Is there any plan to release 0.10.6? :)
I'd like to upgrade Apache Spark to use Py4J 0.10.5, but Spark unit tests are hitting this bug.

**Comment by bartdag** [comment]
Hi, I hope to release 0.10.6 this week, but I'm waiting after the reporter of #275 who needs to validate the fix for the last issue of this milestone.

**Comment by dongjoon-hyun** [comment]
Oh. Great! Thank you so much!
