### ISSUE TITLE
Java ClientServer doesn't use its SocketFactory

### ISSUE THREAD

**Issue by leifwalsh** [bartdag/py4j#284]
`ClientServer` helpfully allows you to pass in a `ServerSocketFactory` and a `SocketFactory` to be used, except in `ClientServer.createPythonClient`, it ignores that member and uses `SocketFactory.getDefault` instead.

**Comment by bartdag** [comment]
Indeed, that will be easy to fix. thanks for reporting this bug!

**Comment by leifwalsh** [comment]
Thanks!
