### ISSUE TITLE
Connecting a JDBC driver via py4j?

### ISSUE THREAD

**Issue by h5rdly** [bartdag/py4j#288]
Hi,

First of all, cheers for creating this nice package.

I'm trying to run some tests on a JDBC driver, and was wondering whether/how it can perhaps be done in Python via py4j. 

Is there a way to do it, specifically without tinkering with the driver?

Thanks,
Eli

**Comment by bartdag** [comment]
Hi, it is possible to use Py4J with JDBC. You can launch a JVM using launch_gateway, make sure that the JDBC driver jar is in the classpath (one of the options of launch_gateway) and then interact with JDBC from Python.

**Comment by bartdag** [comment]
Please reopen if needed.
