### ISSUE TITLE
jruby support?

### ISSUE THREAD

**Issue by AlJohri** [bartdag/py4j#289]
I have a wrapper for a java library written in jruby which I currently expose via REST and use in my python apps. Is there anyway I can directly call the jruby library from python? I think I can convert the jruby library into a `jar` file (https://github.com/jruby/jruby/wiki/StandaloneJarsAndClasses#standalone-executable-jar-files) but I was wondering if anyone has tries this before. Thanks!

**Comment by bartdag** [comment]
While it could theoretically work (you can create a GatewayServer from JRuby), it would probably be very difficult to call JRuby from Python. You would need to find how to invoke a JRuby function using Java reflection first.

**Comment by bartdag** [comment]
Please reopen if needed.
