### ISSUE TITLE
Pyinstaller 3.3 - where is jar file for py4j?

### ISSUE THREAD

**Issue by xeaa2ll** [bartdag/py4j#290]
Script runs under 3.4.x interpreter. I am using jaydebeapi as the wrapper for py4j.

I'm building a binary with pyinstaller 3.3, and I get installer to include the jar file. I verified that with the analyzer utility which is part of pyinstaller. I specified the runtime location as '.'.
binaries=[('c:\\Users\\xeaa2ll\\AppData\\Local\\Programs\\Python\\Python34_32\\share\\py4j\\py4j0.10.6.jar', '.')]
That still results in the gateway not loading the jar. Where should it go?

**Comment by bartdag** [comment]
Hi, sorry for the very long delay, you may have better luck next time on the mailing list for support requests. Is this still a problem? If it is, can you provide more details about the error, I am unfamiliar with jaydebeapi and pyinstaller.

**Comment by xeaa2ll** [comment]
I was not sure if this is a bug or just my setup. I don't have root access
on the company servers, so I am doing local installation of python. At
first I did not know about the --enabled-shared configure options (I'm just
learning this from posts on StackExchange). I found that when I tried to
build sqlite3 and needed the libraries (other story, needed the TRIM
function from 10 years ago, so I needed to upgrade sqlite3)

I'm just doing a pip install of the JDBC interface  and then trying to
build an executable so I can run it on a machine in production without
having to place the Python there too. The initial testing was on Windows
and PyInstaller did build the exe it would not run as it could not
find JPype1 at run time (Python 3.4.7, still trying with the hook_*
members). I'm trying to move to 3.5 or 3.6 on Linux (3.6 has install issues
for other libraries) and 3.5 is working from command line. It just won't
build an executable, no JDBC or with JDBC (I have both types to create and
run).

I am off-line from the office right now. If you tell me how to properly
report this I will switch channels to that method.

I've been doing Python for a few years but am really just a novice with it,
can't claim to be more even after 4 decades of working with computers (know
what an O036 is?). If I get to the end result I need, I'm happy. I report
and ask questions if I'm really stumped and want to reach the end for a
given project.



Thanks,
Ed

**Comment by bartdag** [comment]
Hi, thanks for the follow-up.

Do not hesitate to post your support questions on the mailing list: https://groups.google.com/a/py4j.org/forum/#!forum/py4j/join

If I understand correctly, you are using pyinstaller to create an executable that bundles py4j and there is a problem with the jar not being bundled or being bundled but extracted at an unusual location during installation. When writing to the mailing list, please specify how you are starting the JVM (e.g., by calling launch_gateway or ...?) and the exact errors you are encountering.

Thanks!
