### ISSUE TITLE
NullPointerException when a function returns an object

### ISSUE THREAD

**Issue by Tagar** [bartdag/py4j#292]
Sometimes py4j causes NPE when a function returns an object.
For example, in Spark/Hadoop environment:

    hadoop = sc._jvm.org.apache.hadoop
    dst_path = hadoop.fs.Path(dst_file)
    out_stream = hadoop.fs.FileSystem.create(dst_path, overwrite)

causes 

>   File "/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
>     answer, self.gateway_client, self.target_id, self.name)
>   File "/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/sql/utils.py", line 63, in deco
>     return f(*a, **kw)
>   File "/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 323, in get_return_value
>     format(target_id, ".", name, value))
> Py4JError: An error occurred while calling z:org.apache.hadoop.fs.FileSystem.create. Trace:
> java.lang.NullPointerException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:280)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:214)
> 	at java.lang.Thread.run(Thread.java:748)
> 

org.apache.hadoop.fs.FileSystem.create()
returns FSDataOutputStream (defined [here](https://goo.gl/SntBEB)  )
and this returned object type somehow causes NPE.
Is this a know issue?

In other cases returning an object works fine.

**Comment by bartdag** [comment]
That's strange. It seems that the NPE occurred in invoke0 so this looks like a problem with the invocation.

If possible, I would use version 0.10.6 just to rule out any possible bugs that were already squashed (but I don't think a previous bug fix applies for this case).

Then I would try the exact same code in Java just to rule out your particular Hadoop setup.

Then I would try to add as much debug information as possible (print(dst_path.getClass().getName() and print(type(overwrite)). Although the code looks simple enough, maybe there is some type conversion problem because create is overloaded and Py4J may end up guessing the wrong method.

Another test: pass overwrite and path to a Java method that itself calls create(). Does it work?

You also mention "Sometimes py4j causes NPE when a function returns an object.". Is this the only occurrence when a NPE occurs? Py4J is not known to cause random NPE in user code, so do not hesitate to report other cases.

**Comment by Tagar** [comment]
Thanks for prompt response @bartdag 

> If possible, I would use version 0.10.6 just to rule out any possible bugs that were already squashed (but I don't think a previous bug fix applies for this case).

We're bound to use what Spark is compiled with, which is 0.10.4 for Spark 2.2.

> Then I would try to add as much debug information as possible (print(dst_path.getClass().getName() and print(type(overwrite)). 

Produces following output:

> org.apache.hadoop.fs.Path
> <type 'bool'>
> 


> Another test: pass overwrite and path to a Java method that itself calls create(). Does it work?

In PySpark we can only use Python code.. I'm not familiar with py4j if it could execute/eval() an anonymous snippet of Java code?

> Although the code looks simple enough, maybe there is some type conversion problem because create is overloaded and Py4J may end up guessing the wrong method.

Yes, create is overloaded, and our call matches following method:

```
public FSDataOutputStream create(Path f,
                        boolean overwrite)
                          throws IOException

```

**Comment by bartdag** [comment]
After looking at the class documentation and your code, I see that you are invoking create() as if it was a static method, but it's an instance method hence the null pointer exception (this [SO question](https://stackoverflow.com/questions/18802277/getting-java-lang-nullpointerexception-when-calling-method-invoke) got me on the right track).

**Comment by Tagar** [comment]
You're right - thanks for catching that.
It seems there is only one static create() method in hadoop.fs.FileSystem
https://goo.gl/kpGUZz
with signature 
```
public static FSDataOutputStream create(FileSystem fs,
                        Path file,
                        FsPermission permission)
                                 throws IOException

```

Thank you @bartdag

**Comment by Tagar** [comment]
I got it working ... thanks again
