### ISSUE TITLE
Disabling massive DEBUG output

### ISSUE THREAD

**Issue by qvad** [bartdag/py4j#299]
I've complex test using your library with shutting down JVM with gateway and creating a new one from same jar/class.

This is logic of test:
1. Create JVM and start gateway, run some internal process
2. Do smth
3. Shutdown internal process in JVM, shutdown gateway, kill jvm
4. Trying to run new JVM from same class, run internal process

While passing this scenario I've got following messages:

```
....
~10k lines here
....

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: m
d
o7308
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: m
d
o7309
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: m
d
o7310
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: m
d
o7311
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: m
d
o7312
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: m
d
o7313
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Command to send: c
t
close
e

py4j.java_gateway: DEBUG: Answer received: !yv
py4j.java_gateway: DEBUG: Exception while shutting down a socket
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/py4j/java_gateway.py", line 461, in quiet_shutdown
    socket_instance.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
py4j.java_gateway: DEBUG: Exception while shutting down a socket
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/py4j/java_gateway.py", line 461, in quiet_shutdown
    socket_instance.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor
py4j.java_gateway: DEBUG: Command to send: r
u
py4j
rj
e
```

I've found the same issue with restarting JVM with gateway here but I can't find solution for disabling logging

Also Exceptions in this log do nothing.

**Comment by qvad** [comment]
Sorry.
Looks like the only problem is just massive debug log

**Comment by bartdag** [comment]
Exceptions logged at the debug level are to be expected when shutting down a gateway. The only one that is a little out of place is the ERROR log statement, but that's just difficult at this point in the code to determine whether it's a real problem or it's caused by a shutdown.

If no exceptions are raised, then you are good to go (expected connectivity exceptions are all caught during shutdown and are not re-raised)

**Comment by qvad** [comment]
Can I turnoff this DEBUG output?

The problem is that we are using nosetests for our testesuite. When any step fails, then this framework outputs all logs (including py4j). There is a lot of data in py4j DEBUG. (like 5-10k lines)

**Comment by bartdag** [comment]
I think it is caused by nose logcapture plugin (enabled by default). You can try to pass `--logging-level=INFO` to nose. Ref: http://nose.readthedocs.io/en/latest/plugins/logcapture.html#cmdoption-logging-level

**Comment by bartdag** [comment]
Please reopen if needed.
