### ISSUE TITLE
Py4j can make Java access python third-party libraries , for example:numpy, if can, how to use

### ISSUE THREAD

**Issue by ganhb** [bartdag/py4j#305]
As title show

**Comment by jonahkichwacoders** [comment]
Yes it can. Simply define a Java interface with a matching Python implementation of that interface. See [Initiating the communication from the Java side](https://www.py4j.org/advanced_topics.html#initiating-the-communication-from-the-java-side). Using this method allows you to access anything in Python, just define an appropriate Java interface and perhaps the Python glue code. In addition, if you want to move Numpy arrays between Java and Python, you will need a way to represent them in Java. One option is [Eclipse January](https://eclipse.org/january/), but you could just use double arrays.

I hope that helped.

**Comment by ganhb** [comment]
Thank you very much. But I found performance is a problem when implemented, unlike [the official website said](https://docs.google.com/spreadsheets/d/14ljMYIESFbOBFe4o_Fy6WirI2P5iCQuTP9fA1BuLMAI/pubchart?oid=935988429&format=interactive),I use jprofile, found in ![Aaron Swartz](http://chuantu.biz/t6/213/1516762428x-1404793447.png)
I use 10000000 data each time 5000

**Comment by jonahkichwacoders** [comment]
What type are you transferring? IIRC the performance for transferring large data is only optimized for byte arrays.

**Comment by ganhb** [comment]
Just a few varchar type data, nothing else, I debug blocked on readline (), my value has made sure there is no null and ends with '\n', maybe I'm using a pinned thread model?

**Comment by ganhb** [comment]
Just a few varchar type data, nothing else, I debug blocked on `returnCommand = this.readBlockingResponse(this.reader),`just readline, my value has made sure there is no null and ends with '\n', maybe I'm using a pinned thread model?

**Comment by jonahkichwacoders** [comment]
Can you post your whole example?

**Comment by ganhb** [comment]
java
`static {
		clientServer = new ClientServer(null);
		demotest = (IDemo) clientServer.getPythonServerEntryPoint(new Class[] { IDemo.class});
	}
	
	@Override
	protected IDataSet exec(IDataSet e) throws Exception {
		for(int i=0;i<e.getSize();i++){
			for(TransExpSubString subString:subStrings){
				Object columnVal=e.getCellValue(i,subString.getOutStreamName());
				if (columnVal == null) {
					continue;
				}
				e.setCell(i, subString.getOutStreamName(), birdgePyByPy4j(columnVal.toString()));
			}
			
		}
		return e;
	}

	private String birdgePyByPy4j(String str) {
		return demotest.appendFunc(str);
	}`
python 
`class SimpleDemo(object):

   def appendFunc(self, string_value=None):
      return '{0}\n'.format(string_value)
   class Java:
      implements = ["com.code.etl.plugin.transition.IDemo"]

from py4j.java_gateway import JavaGateway, CallbackServerParameters
simple_demo = SimpleDemo()
gateway = JavaGateway(
    callback_server_parameters=CallbackServerParameters(),
    python_server_entry_point=simple_demo)`

**Comment by jonahkichwacoders** [comment]
It does not look like you are sending byte arrays back and forth. IIRC it is only byte arrays that have an optimised path. So you need to convert your data to bytes, send it, and then convert back if performance of large data is important. py4j handles small data very well, and large data as byte arrays well. PS If you can fix the formatting of your post it will make it easier for future readers, also a fully runnable minimal example is useful.

(If general support for large data is needed, then perhaps you can consider some funded development?)
