### ISSUE TITLE
Py4JJavaError.__str__ should return string in Python 2

### ISSUE THREAD

**Issue by HyukjinKwon** [bartdag/py4j#306]
Currently, seems `__str__`:

https://github.com/bartdag/py4j/blob/aa6c53b59027925a426eb09b58c453de02c21b7c/py4j-python/src/py4j/protocol.py#L423-L427

could return `unicode` in Python 2.

1. The version of Py4J, Python, and Java you are using (e.g., 0.10.1, 3.5.1, 8)

    ```python
    >>> py4j.__version__
    '0.10.6'
    ```

2. The OS your are using (Windows 7, OSX Yosemite, Ubuntu 16.04)

    ```bash
    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.12.6
    ...
    ```

3. A snippet of code that can reproduce the problem

    For example, I have an exception:

    ```python
    >>> repr(e)
    "Py4JJavaError(u'An error occurred while calling o99....\\n', JavaObject id=o100)"
    ```

    For details, it follows as below:

    ```python
    >>> from __future__ import unicode_literals
    >>> from py4j.protocol import get_return_value
    >>> gateway_client = e.java_exception._gateway_client
    >>> answer = gateway_client.send_command(e.exception_cmd)
    >>> return_value = get_return_value(answer, gateway_client, None, None)
    >>> type(e.errmsg)
    <type 'unicode'>
    >>> type(return_value)
    <type 'unicode'>
    >>> "{0}: {1}".format(e.errmsg, return_value)
    u'An error occurred while calling o99 ...
    ```

    My error message contains non-ascii compatible characters like `"아"`. and I can't get the proper string from the exception:

    ```python
    >>> str(e)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 292-296: ordinal not in range(128)
    ```

    I understand the difference between `str` and `unicode` which are bytes and unicode points but this is kind of weird:

    https://github.com/bartdag/py4j/blob/aa6c53b59027925a426eb09b58c453de02c21b7c/py4j-python/src/py4j/protocol.py#L412

    is unable to print an exception. Also, I believe technically `__str__` in Python 2 should return a `str`, not relaying on type coercion.

    This might be trivial but I raised this issue here because it needs a special handling in my application (PySpark). Workaround seems to be directly call `__str__` or `unicode` and encode it manually.

    I would like to propose at least fix the documentation.

**Comment by bartdag** [comment]
Thanks for the detailed bug report!

If I understand correctly, the exception UnicodeEncodeError is raised in your code and not in Py4J code because you are trying to convert a non-ascii unicode string to a bytestring using str() 

Did you try to do `e.encode('utf-8') # or use the same encoding as the one on the Java side`?

Although it's true that Python 2 should return a bytestring with __str__, in that particular case, it is interacting with Java so it will always have to deal with unicode. We could try to detect if Python 2 is running and do the same thing as suggested above (`.encode('utf-8')`), but at this point it would be a backward incompatible change.

**Comment by HyukjinKwon** [comment]
Yea, that should work and wanted to add this workaround in PySpark or my application but was wondering if this could be simply done in Py4J first, or documented.

Can we add a simple note in the docstring? Meanwhile, will fix it in PySpark or my application.
