### ISSUE TITLE
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:25333)

### ISSUE THREAD

**Issue by iamadou** [bartdag/py4j#307]
I' m trying to connect from python to java side application.
Java side application is in running mode 
GatewayServer gatewayServer = new GatewayServer(app, 25333);

Python side 
gateway = JavaGateway(gateway_parameters=GatewayParameters(address='127.0.0.1', port=25333))
if gateway is None:
    print("gateway is running")
    rd = gateway.entry_point.getCalcul()
It's block during the connection step. 
I using py4j.0.10.1.jar version, Linux, python2.7

**Comment by bartdag** [comment]
Hi, Py4J 0.10.1 is a bit old now, but I don't think it is the problem... Can you try to explicitly provide 127.0.0.1 to GatewayServer? The problem is that some system interprets "localhost" as being a IPv6 address so the python side might be trying to use IPv4 and the Java side might be waiting for a IPv6 connection. If you also use a firewall that is very strict, it might block all ports by default.

**Comment by iamadou** [comment]
Hi, 
I switched to the Py4J0.10.6 version yesterday. I don't have any enabled Firewall on my PC. But when I try to put the third parameter, of type ``InetAddress`` like this ``InetAddress address = InetAddress.getLocalHost()``  without by considering other as default value, it is saying the  ``The constructor GatewayServer(JavaGatewayServer, int, InetAddress) is undefined`` . Should I define also other parameters? If yes, How should  I define command List parameter?

The python side trace is:
 ``ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 777, in start
    self.socket.connect((self.address, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused``

What I forgot to say is my java side application is an executable jar generated through maven with eclipse.

**Comment by Vonisoa** [comment]
I'm facing the same error, can you tell please how did you solve it?
