### ISSUE TITLE
Fail to call the java method with "Arbitrary Number of Arguments"

### ISSUE THREAD

**Issue by chialingwang** [bartdag/py4j#322]
This is the method in java:
```
	public Query<T> addField(String... fieldNames) {
		//		Element element = new Element(fieldName);
		//		queryElement.addChild(element);
		for (String fName : fieldNames) {
			Element e = new Element(fName);
			queryElement.addChild(e);
		}
		return this;
	}

	public Query<T> addEquals(String fieldName, String value) {
		Element element = new Element(fieldName);
		element.setAttribute("operator", "equals");
		element.setCData(value);
		queryElement.addChild(element);
		return this;
	}
```

And when I called this method in python with only one string as argument, it shows error.

My python code:
```
gateway = JavaGateway(auto_field=True)
entry = gateway.entry_point 
query = entry .getQuery("Date")
query.addField("This is field name");
```

It shows error:

> Py4JError: An error occurred while calling o587.addField. Trace:
> py4j.Py4JException: Method addField([class java.lang.String]) does not exist
> 	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
> 	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
> 	at py4j.Gateway.invoke(Gateway.java:274)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Unknown Source)

However, if I called
`query.addEquals("field", "0");`
it ran successfully.

So, I believe the problem should be the py4j could not recognize method with arbitrary number of arguments (ex. String...)

Is there anything I can work around with?
Thanks!

**Comment by bartdag** [comment]
Did you try sending an array of string? I believe var args have been discussed in issues and on the mailing list in the past. Internally varargs are just arrays.

**Comment by chialingwang** [comment]
Thank you so much! 
After I pass in as string array, it works!

```
string_class = gateway.jvm.String
string_array = gateway.new_array(string_class, 1)
string_array[0] = "field"
```
