### ISSUE TITLE
Unable to run addition example: "Target Object ID does not exist for this gateway"

### ISSUE THREAD

**Issue by Tenceto** [bartdag/py4j#332]
I tried to run [the addition example](https://www.py4j.org/) offered in the website. This is the code:

```
from py4j.java_gateway import JavaGateway
JavaGateway.launch_gateway(port = 25333)
gateway = JavaGateway()
random = gateway.jvm.java.util.Random()
number1 = random.nextInt(10)
number2 = random.nextInt(10)
sum_value = gateway.entry_point.addition(number1, number2)
```

I'm getting the following error:

```
Py4JError: An error occurred while calling t.addition. Trace:
py4j.Py4JException: Target Object ID does not exist for this gateway :t
	at py4j.Gateway.invoke(Gateway.java:279)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)
```

Sorry if this is way too basic, I've never programmed in Java before, just Python. How can I fix this and why is this happening?

**Comment by bartdag** [comment]
Hi, the addition example does not include the launch_gateway line. You need to start the JVM yourself before running the Python code. You also need to include the Java code in the example (it is not included in Py4J's jar).

**Comment by Tenceto** [comment]
Thanks for the help!
