### ISSUE TITLE
py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by dHannasch** [bartdag/py4j#345]
Like many libraries (e.g. https://github.com/scikit-learn/scikit-learn/issues/11121), java_collections started getting hit with the collections.abc DeprecationWarning in Python 3.7:

```
py4j/java_collections.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import (
```

https://github.com/bartdag/py4j/blob/master/py4j-python/src/py4j/java_collections.py
```
from collections import (
    MutableMapping, Sequence, MutableSequence,
    MutableSet, Set)
```
We could probably just try `from collections.abc import` and if that raises an ImportError then `from collections import`.

**Comment by bartdag** [comment]
Hi, can you make a pull request with your changes (and an inline comment explaining why we try .abc first)?

Thanks for reporting this deprecation warning, it definitively went under my radar.

**Comment by fabiencelier** [comment]
Hi,
Is it possible to merge this PR or explain what need to be improved ?

**Comment by fabiencelier** [comment]
Hi @bartdag 
Is it possible to do a release with this fix to be more compatible with the incoming python 3.8 ?

**Comment by zacchiro** [comment]
> Hi @bartdag
> Is it possible to do a release with this fix soon to be more compatible with the incoming python 3.8 ?

Yes, please, with 3.8 now released a new release integrating this would be great.

And thanks a lot @bartdag for maintaining py4j !

**Comment by hugovk** [comment]
They decided to postpone this removal from Python 3.8 to 3.9.

Python 3.9 is now in alpha with a release due in October, and py4j doesn't work in 3.9. For example, here's a Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1791969

It would be great to have a new release for people working on the upcoming 3.9.

Thanks!

**Comment by bartdag** [comment]
Hi all! Thanks for you patience. I just published a release, 0.10.9, that includes the fix for this issue.

**Comment by hugovk** [comment]
Thank you for the release! 
https://pypi.org/project/py4j/0.10.9/

Please could you also tag it? 
https://github.com/bartdag/py4j/releases

**Comment by bartdag** [comment]
@hugovk thanks. It was tagged locally but I forgot to push it. Done.
