### ISSUE TITLE
ERROR:root:Exception while sending command. Traceback (most recent call last):   File "C:\spark-2.3.2-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1159, in send_command     raise Py4JNetworkError("Answer from Java side is empty") py4j.protocol.Py4JNetworkError: Answer from Java side is empty

### ISSUE THREAD

**Issue by adityasinghcdacnoida** [bartdag/py4j#347]
I am using jupyter notebook with pyspark and mleap
running this line of code--
**gbtModel.serializeToBundle("jar:file:/tmp/new1_diamonds.zip", predictions.limit(0))**

ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "C:\spark-2.3.2-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\spark-2.3.2-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "C:\spark-2.3.2-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-51-fdcad7b6fb9e> in <module>()
----> 1 gbtModel.serializeToBundle("jar:file:/tmp/new1_diamonds.zip", predictions.limit(0))

C:/mleap/python\mleap\pyspark\spark_support.py in serializeToBundle(self, path, dataset)
     22 
     23 def serializeToBundle(self, path, dataset=None):
---> 24     serializer = SimpleSparkSerializer()
     25     serializer.serializeToBundle(self, path, dataset=dataset)
     26 

C:/mleap/python\mleap\pyspark\spark_support.py in __init__(self)
     37     def __init__(self):
     38         super(SimpleSparkSerializer, self).__init__()
---> 39         self._java_obj = _jvm().ml.combust.mleap.spark.SimpleSparkSerializer()
     40 
     41     def serializeToBundle(self, transformer, path, dataset):

C:\spark-2.3.2-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __getattr__(self, name)
   1596                 answer[proto.CLASS_FQN_START:], self._gateway_client)
   1597         else:
-> 1598             raise Py4JError("{0} does not exist in the JVM".format(new_fqn))
   1599 
   1600 

Py4JError: ml.combust.mleap.spark.SimpleSparkSerializer does not exist in the JVM

**Comment by bartdag** [comment]
Hi, this is probably best answered on pyspark mailing list or other support channels.
