### ISSUE TITLE
Setting an array element to a null value

### ISSUE THREAD

**Issue by jdgarrett** [bartdag/py4j#371]
When doing the following:
```
gateway = JavaGateway()
string_class = gateway.jvm.String
str_array = gateway.new_array(string_class, 2)
str_array[0] = "test"
str_array[1] = None
```

I get the following exception:
```
py4j.protocol.Py4JError: An error occurred while calling None.None. Trace:
java.lang.NullPointerException
	at py4j.commands.ArrayCommand.convertArgument(ArrayCommand.java:154)
	at py4j.commands.ArrayCommand.setArray(ArrayCommand.java:144)
	at py4j.commands.ArrayCommand.execute(ArrayCommand.java:97)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

With Java, you can have null values in an object array, so I would expect this to work.  Is there a work around for this?

**Comment by jdgarrett** [comment]
After digging into this further, I found that the array is initialized with null values, so the answer is to simply not set the element that should be null.  If a non-null element needs to be set back to null, it can be done via:
```
gateway.jvm.java.lang.reflect.Array.set(str_array, 1, None)
```
It would still be nice for `str_array[1] = None` to work though.

**Comment by bartdag** [comment]
This is actually a bug in the ArrayCommand. Py4J handles null value just fine when calling a method or constructor and it should work too when setting an array element to null.

The line:

```java
		Class<?>[] argumentClasses = { objectToSet.getClass() };
```

should check if the objectToSet is null before calling .getClass(). A call to `gateway.getReflectionEngine().getClassParameters(new Object[] {objectToSet})` would probably do just that.
