### ISSUE TITLE
py4j/java_gateway.py: DeprecationWarning: invalid escape sequence \*

### ISSUE THREAD

**Issue by AbdealiJK** [bartdag/py4j#377]
When I run pytest on some Spark (2.4.3) application, I get a warning from py4j which says:
```
/usr/local/hadoop/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py:2020
  /usr/local/hadoop/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py:2020: DeprecationWarning:

  invalid escape sequence \*
```

On digging into the zip file, i found this is happening due to the `\*` in the docstring at:
https://github.com/bartdag/py4j/blob/7d931a9c41d122ea9cfdc76a322f6706c45eedda/py4j-python/src/py4j/java_gateway.py#L2062

This happens with Python 3.6 as mentioned in the deprecated behavior release notes:
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError, that will not be for several Python releases. (Contributed by Emanuel Barry in bpo-27364.)

While not critical at the moment, it would be good to avoid this so that warnings don't pop up. And this will later become a SyntaxError.

A quick google search shows there were similar issues in other libraries:
https://github.com/pallets/flask/pull/3056

**Comment by bartdag** [comment]
Thanks for this bug report!

I was surprised at first, but it makes sense that the interpreter is actually interpreting these strings (available through __doc__). I also learned that there is such a thing as a raw docstring (r"""..."""), which may be easier on the eye in this case.
