### ISSUE TITLE
Find FQN based on a SimpleName

### ISSUE THREAD

**Issue by bartdag** [bartdag/py4j#40]
This one probably won't be easy, especially with multiple classloaders (hello Eclipse). But there should be some equivalent to Eclipse Ctrl-Shift-O to find a FQN on the fly.

**Comment by 243826** [comment]
Bathe, I may be able to help on a few pull request as the time permits. Was looking at this one - i think we should just close it - 1. i do not see a huge utility and it has been pending for more than 5 years.

**Comment by bartdag** [comment]
Well, it might be useful, but there are more pressing concerns and you are right that nobody asked for it since it was open. Let's close it.
